### ISSUE TITLE
[新功能] Features & Improvements

### ISSUE THREAD

**Issue by realgooseman** [sh0ckj0ckey/Flint#2]
> **_文本由非母语人士自动翻译。如有语法错误，敬请原谅。_**

嗨，@sh0ckj0ckey、

很棒的小程序，干得漂亮。
我想对 Flint 提出一些功能/改进建议，请告诉我你的想法。

### **可见性**
很难找到 Flint，因此，作为一款免费的开源应用程序，在 [AlternativeTo](https://alternativeto.net/) 等网站上发布它将有助于普及该应用程序并获得更多知名度。

### **本地化**
目前，我相信这款应用程序只有中文版，如果能实现与多语言界面的兼容，对国际化将大有裨益。例如，建立一个 [Crowdin](https://crowdin.com/)面板，让人们参与翻译。

### **更多字典来源**
添加更多字典资源将极大地促进国际化。例如 ：

- 必应词典
- 谷歌词典
- 维基词典
- 自由词典
- ...

这些开源项目实现了字典插件，也许值得一看代码？

[Dictionariez](https://github.com/pnlpal/dictionariez)
[Pot Desktop](https://github.com/pot-app/pot-desktop)

> **_基本文本（资料来源）_**

> Hi @sh0ckj0ckey,
> 
> Great little app, nice work.
> I would like to suggest some features/improvements for Flint, let me know what you think.
> 
> ### **Visibility**
> It was quite hard to find Flint, so as a free and open-source app it would be useful to publish it on websites like [AlternativeTo](https://alternativeto.net/) to popularize the app and get more visibility.
> 
> ### **Localization**
> Currently the app is only available in Chinese I believe, Implementing compatiblity with multi-lingual interfaces would be great for internationalization. By setting up a [Crowdin](https://crowdin.com/) panel and letting people contribute in translations for example.
> 
> ### **More dictionary sources**
> Adding more dictionary sources would be great for internationalization. For example : 
> 
> - Bing Dictionary
> - Google Dictionary
> - Wiktionary
> - The Free Dictionary
> - ...
> 
> These open source projects implemented dictionary plugins, maybe it's worth taking a look at the code ?
> 
> [Dictionariez](https://github.com/pnlpal/dictionariez)
> [Pot Desktop](https://github.com/pot-app/pot-desktop)

**Comment by sh0ckj0ckey** [comment]
Hello @realgooseman, thank you very much for your detailed advice, it is very valuable to me!

Unfortunately, I've been quite busy with work lately and working on my other two apps (Honeypot and Summer), so the development of the Flint update might be postponed until March.

Regarding the localization of Flint, I happen to have recently learned how to support multiple languages in WinUI3 programs, so I'll have Flint supporting English by then!

As for the feature of more dictionary sources, this is a feature I'm going to add in the next major update, I'll try to make Flint support multiple online search capabilities, and I'll have a look and learn about the software you mentioned. Thanks a lot!

It's a difficult thing for Flint to promote, but even if Flint is little known at the moment, I will continue to develop new features 😀.

By the way, it looks like you are not Chinese, what features of Flint do you use? After all, it only supports English to Chinese translation at the moment.

Sorry my English is not good enough, so I used DeepL for the translation 😟.

**Comment by realgooseman** [comment]
Great to hear. Well unfortunately I can't use Flint as I'm not-native. But I found the app very simple and clean looking. So I look into the future of the app.

You're perfectly understandable, even with DeepL (which I used too by the way).

**Comment by sh0ckj0ckey** [comment]
It's very kind of you! Thank you very much for your suggestions, which I will carefully consider and incorporate on a case-by-case basis. 
Best wishes for your happiness in the New Year🥰.
