### ISSUE TITLE
小功能建议

### ISSUE THREAD

**Issue by max-yeah** [sh0ckj0ckey/Flint#3]
感谢开发，这个工具完美符合了我的需求，能离线查词而且很简洁。
我有两个使用过后的小建议：
1. 希望软件能记住用户调整过后的窗口的位置以及大小。场景是：用户把软件的窗口调整成小一点的size，但是重启系统之后又会恢复默认大小。
2. 希望能增加开机自动启动的选项，我指的是运行在右下角系统托盘tray而非跳出主搜索框，供用户选择是否开启。场景是：每次用户重启系统，不需要手动点击来初次运行软件，也可以直接使用alt+空格这种快捷键开始使用软件。

**Comment by sh0ckj0ckey** [comment]
@max-yeah 你好👋，十分感谢你的建议，这两条都非常有价值，我后续会逐一添加上去，不过近期比较繁忙，所以可能会晚一些😢
至于保存窗口尺寸和位置，目前是在应用正常退出时会保存下来，但是比如直接关机，则不会保存了，我后面会改成实时的保存就可以解决啦

**Comment by max-yeah** [comment]
@sh0ckj0ckey Hi! 谢谢回复，不着急的，期待后续的更新。希望软件越做越好同时继续这种简洁的风格

**Comment by sh0ckj0ckey** [comment]
Hi，今天刚刚上传了更新，现在可以在设置中开启开机自启了噢。
而对于窗口尺寸的记录，因为我使用的第三方库已经自带了这个功能，因此我新添加的记录与之产生了冲突而无法生效😟。你可以先将窗口调至合适的尺寸和位置后，右键系统托盘的图标退出，这样就会触发一次保存，后续就会使用新的尺寸和位置啦。

**Comment by max-yeah** [comment]
@sh0ckj0ckey Hi, 非常感谢，我试了下两个功能都很好的实现了👍
